[project]
name = "kotibotti"
version = "0.2.0"
description = "A bot for managing certain aspects of domestic life."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.13.4",
    "pydantic-settings>=2.14.2",
    "python-dotenv>=1.2.2",
    "python-telegram-bot>=22.8",
]

[project.scripts]
kotibotti = "kotibotti.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
